### ISSUE TITLE
 Proposal: Convenience Comparison Methods to ULID type

### ISSUE THREAD

**Issue by pscheid92** [oklog/ulid#100]
Hello everyone,

I've noticed that while we have a `Compare` method for comparing two ULID instances, it might be beneficial to have additional convenience methods for specific comparisons. Specifically, I propose implementing methods like Equal, Less, LessEq, Greater, and GreaterEq.

These methods would essentially be wrappers around the existing Compare method, providing a more intuitive and readable interface for common comparison operations. Here's a rough idea of what these methods could look like:

```go
func (u ULID) Equal(other ULID) bool {
  return u.Compare(other) == 0
}

func (u ULID) Less(other ULID) bool {
  return u.Compare(other) < 0
}

func (u ULID) LessEq(other ULID) bool {
  return u.Compare(other) <= 0
}

func (u ULID) Greater(other ULID) bool {
  return u.Compare(other) > 0
}

func (u ULID) GreaterEq(other ULID) bool {
  return u.Compare(other) >= 0
}
```

I believe these convenience methods would make the library more user-friendly by making the code more readable and reducing the cognitive load on developers.

```go
x := ulid.Make()
y := ulid.Make()

if x.Compare(y) <= 0 {
    // do something
}

if x.LessEq(y) {
    // do something
}
```

I would love to hear your thoughts on this proposal. If there's an agreement, I'm more than willing to work on the implementation and submit a PR.

Best regards,
Patrick

**Comment by peterbourgon** [comment]
As [ulid.ULID is a 16 byte array](https://pkg.go.dev/github.com/oklog/ulid/v2#ULID) it [naturally defines equality via ==](https://go.dev/play/p/ZoO3onEWPUg), so I think Equal is already covered. And while I admit it's subjective, I don't believe the Greater/Less class of methods provide enough value over using Compare directly to justify the expansion of the API.

I'll wait a bit in case @tsenart wants to comment, but at the moment, I guess I'll call this a likely decline.

Still, thank you for the comment and the PR!
