### ISSUE TITLE
Change `.Time()` method on ULID to return time.Time, add `UnixMilli` for returning ms

### ISSUE THREAD

**Issue by tonyhb** [oklog/ulid#106]
It's _really_ common to write `ulid.Time(id.Time())` when using ULIDs.  It would make sense for `.Time()` to return a `time.Time`, and for `UnixMilli()` to return the timestamp as ms.  This mirrors the time package and is more ergonomic.

**Comment by peterbourgon** [comment]
I don't necessarily disagree, but this would represent a breaking change, which is probably a non-starter. What about adding a new method that returns time.Time, maybe Timestamp?
