### ISSUE TITLE
Standalone executable

### ISSUE THREAD

**Issue by alizain** [oklog/ulid#13]
Are you publishing a standalone executable for the `go` version? Someone asked over on my repo, and I wanted to send them your way, because doing it with `go` would be pretty straightforward.

**Comment by tsenart** [comment]
Would be rather easy to do indeed.

**Comment by peterbourgon** [comment]
What does "standalone executable" mean?

**Comment by alizain** [comment]
> What does "standalone executable" mean?

Something you can `brew install` or `apt-get install`

**Comment by peterbourgon** [comment]
I understand that. What would the standalone executable actually do? Can you give an example `ulid -h` output?

**Comment by alizain** [comment]
> Can you give an example ulid -h output?

Functionality wise, I'm thinking something as simple as:

```shell
$ ulid
0000XSNJG0MQJHBF4QX1EFD6Y3
```

```shell
$ ulid 0000XSNJG0MQJHBF4QX1EFD6Y3
Mon, 27 Nov 2017 23:02:49 GMT
```


> ...because ULID encoding/decoding is the domain of code i.e. libraries, not really a commandline tool...

Of course! I'm surprised as well, but there seem to be valid use-cases:
- Some are trying to use `ulid` as a build_id with Docker. So they'd like to run the command line tool and pipe output to a file or some env variable to use later.
- Someone else was trying to use it to bulk import a bunch of ad-hoc CSV files into their database, and felt that the command line was most appropriate place to do it.
- For myself thus far, it's a convenient nice-to-have, nothing else :)

**Comment by peterbourgon** [comment]
Oh, okay, I see. We can easily write a `github.com/oklog/ulid/cmd/ulid` binary that has that behavior. (Nit: you'd probably want to output in a format that included subsecond precision, since ULIDs go to the millisecond.)

**Comment by alizain** [comment]
> (Nit: you'd probably want to output in a format that included subsecond precision, since ULIDs go to the millisecond.)

Yes! Actually, the exact epoch time, instead of a ISO formatted string would be better and more portable.

**Comment by alizain** [comment]
> We can easily write a github.com/oklog/ulid/cmd/ulid binary that has that behavior.

Awesome, thank you! 👍

**Comment by peterbourgon** [comment]
>  the exact epoch time

Epoch is also insufficient as it's only to seconds precision. (We could do our own EPOCH.SUBSECOND e.g. 1511824254.999, perhaps.)

**Comment by alizain** [comment]
Huh. NodeJS and the browser (try `Date.now()`) provide epochs with millisecond precision without a period delimiter. This will need some more research...

**Comment by peterbourgon** [comment]
[Epoch is defined to be](https://en.wikipedia.org/wiki/Unix_time) second precision. Date.now() [returns the number of milliseconds](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now) elapsed since 1 January 1970. Distinct things, I guess!

**Comment by alizain** [comment]
AFAIK and as you've mentioned,
- Unix-time is the number of seconds elapsed since 1 January 1970 (minus leap-seconds)
- The epoch of Unix-time is 1 January 1970 00:00 UTC
- Colloquially, unix-time and epoch-time are used interchangeably.

That being said, [golang's solution](https://gobyexample.com/epoch) seems to be to provide both `Unix` and `UnixNano` (where Unix-time in milliseconds is `UnixNano / 1000`)

Perhaps the best API would be to use a command line flag, to show the encoded time in seconds (with loss of precision but faithfulness to the definition of unix-time) or to show it in milliseconds (with full precision). The two questions that would then remain are:
1. What is the default option?
1. How is the time in milliseconds is displayed (with, or without a period)?

My thoughts on both are:
1. Since we're encoding time in milliseconds, I would err on the side of returning time in milliseconds as well as the default, to be consistent with `ulid`'s spec.
1. Since we're being explicit about returning time in milliseconds, I would err on the side of without a period. However, this would depend greatly on what the standard libraries of popular languages expect and can decode without additional processing. I will look into this some more.

What do you think?

**Comment by peterbourgon** [comment]
Maximum user-friendliness dictates the default option should provide the least ambiguity. Typing `ulid 0000XSNJG0MQJHBF4QX1EFD6Y3` and getting back e.g. `128968173637846` is pretty ambiguous. I propose

```
$ ulid -h
USAGE
    ulid [flags] [ULID]

    If ULID is specified, decode the ULID and print the timestamp.
    If ULID is not specified, generate a ULID with the current time.

FLAGS
    -format rfc3339  Timestamp format when decoding: rfc3339, millisecond, unix
    -local false       Use local timezone instead of UTC

$ ulid 
0000XSNJG0MQJHBF4QX1EFD6Y3

$ ulid 0000XSNJG0MQJHBF4QX1EFD6Y3
2017-11-29T14:15:16.123Z

$ ulid -format millisecond 0000XSNJG0MQJHBF4QX1EFD6Y3
239847239463277
```

How's this?

**Comment by alizain** [comment]
It's much more thorough and well thought-out; fantastic!

A couple thoughts:
- Perhaps we can use `--format` with the full name of the flag, so that we can also use `-f` for the shorter version.
- What do you think about defaulting to always use crypto-grade entropy?

**Comment by sergeevabc** [comment]
Hmm, I see no binary here https://github.com/oklog/ulid/releases/tag/v2.1.0
Could you be so kind to generate one or mere Windows 7 x64 users like me?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by miparnisari** [comment]
@sergeevabc try something like this

```shell
[26/03/24 3:07:23] ~/go/bin  $ go install github.com/oklog/ulid/v2/cmd/ulid@latest
[26/03/24 3:07:28] ~/go/bin  $ ulid 01G760VF7Y7FZ79V65CC42Y5NW

Tue Jul 05 01:51:01.374 UTC 2022
```

**Comment by sergeevabc** [comment]
@miparnisari Thank you, Maria.

For those who are not accustomed to immerse into compiling code, I attach an executable of [ULID v.2.1.0](https://github.com/oklog/ulid/files/15288998/ulid.v2.1.0.zip) that works fine on Windows 7 x64.

**Comment by sergeevabc** [comment]
It looks like there is a more advanced version of ULID console app.

New options are  `-m`, `-n` and `-p`.

[ulid-2025-03-19.zip](https://github.com/user-attachments/files/19350059/ulid-2025-03-19.zip), works fine on Windows 7 x64.

``` console

$ go install -ldflags="-s -w" go.rtnl.ai/ulid/cmd/ulid@latest

$ ulid.exe -h

Rotational ULID debugging utility
Usage: generate or inspect a ULID

Generate:

    ulid [options]

    -n INT, --num INT     number of ULIDs to generate
    -q, --quick           use quick entropy (not cryptographic)
    -m, --mono            use monotonic entropy (for more than one ULID)
    -z, --zero            use zero entropy

Inspect:

    ulid [options] ULID [ULID ...]

    -f, --format string   time format (default, rfc3339, unix, ms)
    -l, --local           use local time instead of UTC
    -p, --path            assumes argument is a path with a ULID filename (strips directory and extension)

Options:

    -h, --help            display this help and exit

$ ulid.exe -n 5 -m
01JPQZ2ZE0FGJR82FP8D4T8WAE
01JPQZ2ZE0FGJR82FP8EY72PPQ
01JPQZ2ZE1ENGB82HSY3WHMYZY
01JPQZ2ZE1ENGB82HSY6Z7B9CD
01JPQZ2ZE1ENGB82HSY9RKJGZY
```
