### ISSUE TITLE
Timestamp problem

### ISSUE THREAD

**Issue by darrylwest** [oklog/ulid#2]
I'm not sure if the output format: 0000XSNJG0MQJHBF4QX1EFD6Y3 is correct from the example.  The leading zeros don't look right when compared with ulid's generated in other languages.  So I made a slight change to the demo:

var entropy := rand.New(rand.NewSource(time.Now().UnixNano()))
func ExampleULID() {
    var ts uint64 = uint64(time.Now().UnixNano() / 1000000)
    value, _ := ulid.New(ts, entropy))
    fmt.Println(value.String())
    // Output: 01B3QSN2GDP1G124W1Q8D4PD1N
}

This seems to match encoded times from other implementations.

**Comment by tsenart** [comment]
@darrylwest: `ExampleULID` is creating an ULID with `time.Unix(1000000, 0)`. That's `1000000` UNIX seconds which is equivalent to `1970-01-12 13:46:40 +0000 UTC`. The leading zeroes are correct.
