### ISSUE TITLE
UUID compatibility

### ISSUE THREAD

**Issue by vtolstov** [oklog/ulid#27]
Does it possible to add function that returns uuid compat 36 character string?
I have some software that needs 36 character string like uuid ([]byte, and string representation with -)

**Comment by tsenart** [comment]
>  I have some software that needs 36 character string like uuid ([]byte, and string representation with -)

Why don't you use UUIDs, then?

**Comment by vtolstov** [comment]
ULID faster?=) And i like alphanum sorting =)

**Comment by kirillx** [comment]
Imho you can use uuid package for that and convert whenever you want.

**Comment by tsenart** [comment]
Seems easy enough. Not worth to add the dependency to the library.

```go
package main

import (
	"fmt"
	"math/rand"
	"time"

	"github.com/google/uuid"
	"github.com/oklog/ulid"
)

func main() {
	rng := rand.New(rand.NewSource(time.Now().UnixNano()))
	id := ulid.MustNew(ulid.Now(), rng)
	fmt.Println(uuid.FromBytes(id[:]))
}
```

**Comment by vtolstov** [comment]
Thanks!
