### ISSUE TITLE
[Question] Replace math.Rand with crypto.Reader in README maybe?

### ISSUE THREAD

**Issue by kron4eg** [oklog/ulid#3]
I've benchmarked ULID with different sources of entropy and found that with `crypto.rand.Reader` it works 10 times faster then `math.Rand`, at least on MacOS, it's very possible on linux it will behave different.

So maybe it's for better to change README to:

    import "crypto/rand"
    
    func ExampleULID() {
        t := time.Unix(1000000, 0)
        fmt.Println(ulid.MustNew(ulid.Timestamp(t), rand.Reader))
        // Output: 0000XSNJG0MQJHBF4QX1EFD6Y3
    }

How do you think? I can submit benchmarks code if you will although those are trivial.

**Comment by tsenart** [comment]
I'm not sure how you're seeing those results. I'm also running on MacOS and using `crypto/rand.Reader` is an order of magnitude slower. I pushed a commit with these benchmarks (`WithCryptoEntropy`): https://github.com/oklog/ulid/commit/6aab84be89c0cf2186c314df7c080721ba59e6fd

**Comment by kron4eg** [comment]
I think I've put rand.New call inside the loop, to provide new seed every time, and this is where it took 11000ns/op :)

**Comment by tsenart** [comment]
Happens :-) Can this be closed then?

**Comment by kron4eg** [comment]
Yes, thanks for your time!
