### ISSUE TITLE
Generation of new ULID is not thread safe 

### ISSUE THREAD

**Issue by shogus** [oklog/ulid#33]
In order to reproduce, write tests that execute in parallel (or spawn multiple routines) that attempt to create a new ULID (MustNew / New) at the same time.
Eventually it will fail with  DATA RACE error.

Read at 0x00c0000d9500 by goroutine 9:
  math/rand.(*rngSource).Int63()
      /usr/local/go/src/math/rand/rng.go:239 +0x3e
  math/rand.(*Rand).Int63()
      /usr/local/go/src/math/rand/rand.go:85 +0x50
  math/rand.(*Rand).Int63-fm()
      /usr/local/go/src/math/rand/rand.go:264 +0x41
  math/rand.read()
      /usr/local/go/src/math/rand/rand.go:272 +0xcb
  math/rand.(*Rand).Read()
      /usr/local/go/src/math/rand/rand.go:264 +0x159
  <project>/vendor/github.com/oklog/ulid.New()
      /usr/go-workspace/src/<project>/vendor/github.com/oklog/ulid/ulid.go:82 +0x12a
  <project>/vendor/github.com/oklog/ulid.MustNew()
      /usr/go-workspace/src/<project>/vendor/github.com/oklog/ulid/ulid.go:91 +0x61
  <project>/infrastructure/id.(*ulidHelper).GenerateID()
      /usr/go-workspace/src/<project>/infrastructure/id/ulid_helper.go:36 +0x130
  <project>/infrastructure/id.TestIsValidId_WhenIdIsGenerated_ReturnsTrue()
      /usr/go-workspace/src/<project>/infrastructure/id/ulid_helper_test.go:47 +0x4a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162

**Comment by tsenart** [comment]
This is by design. If you need your entropy source to be thread safe, you need to make it so. Check the README. We can, however, improve the documentation in Go Doc about this. I’ll follow up with it.

**Comment by shogus** [comment]
Thanks a lot for clarification. Somehow I completely missed that.
Much appreciated.

**Comment by shogus** [comment]
closing issue

**Comment by tsenart** [comment]
Improved documentation with: https://github.com/oklog/ulid/commit/f41f974e7fd381ab4f116d484f5df5a4ac7a41ba

**Comment by ivanjaros** [comment]
I just want to ask if this implementation is correct of if maybe each call to String() should provide current timestamp and the New() is flawed?
```
var p *sync.Pool
func init() {
	p = &sync.Pool{
		New: func() interface{} {
			return &generator{r: ulid.Monotonic(rand.New(rand.NewSource(time.Now().UnixNano())), 0)}
		},
	}
}

type generator struct {
	r io.Reader
}

func (g *generator) New() ulid.ULID {
	return ulid.MustNew(ulid.Timestamp(time.Now()), g.r)
}

func String() string {
	g := p.Get().(*generator)
	id := g.New().String()
	p.Put(g)
	return id
}
```

**Comment by peterbourgon** [comment]
It's not wrong, but it is probably overkill and very inefficient.

[Given this code](https://gist.github.com/peterbourgon/49c428c35cecd51601856cc1c40540a8) implementing your pool+generator, compared with initializing a single io.Reader and protecting it with a simple mutex:

```
$ go test -v -race
=== RUN   TestStringPool
--- PASS: TestStringPool (2.71s)
=== RUN   TestStringMutex
--- PASS: TestStringMutex (0.67s)
PASS
ok  	_/Users/peter/tmp	4.411s
```

**Comment by tugberkugurlu** [comment]
@peterbourgon I am not sure `-race` is a most reliable way to test the performance. I ran benchmarks based on your code and it gave the below results:

```
➜  safeulid ✗ go test -bench=. -benchtime=20s
goos: darwin
goarch: amd64
BenchmarkStringPool-4    	    2000	  16017449 ns/op
BenchmarkStringMutex-4   	    1000	  43665860 ns/op
```

Full code:

```go
package safeulid

import (
	"fmt"
	"io/ioutil"
	"sync"
	"testing"
)

func TestStringPool(t *testing.T) {
	testFunc(StringPool)
}

func TestStringMutex(t *testing.T) {
	testFunc(StringMutex)
}

func BenchmarkStringPool(b *testing.B) {
	for i := 0; i < b.N; i++ {
		testFunc(StringPool)
	}
}

func BenchmarkStringMutex(b *testing.B) {
	for i := 0; i < b.N; i++ {
		testFunc(StringMutex)
	}
}

func testFunc(f func() string) {
	var (
		wg      sync.WaitGroup
		workers = 100
		count   = 1000
	)
	for i := 0; i < workers; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for j := 0; j < count; j++ {
				fmt.Fprintf(ioutil.Discard, f())
			}
		}()
	}
	wg.Wait()
}
```
