### ISSUE TITLE
Feature/Generate ULID with lowercase characters

### ISSUE THREAD

**Issue by kimlisa** [oklog/ulid#35]
Is it possible to add a feature to have the final ULID to contain lowercase characters? My team is trying to use this package to generate unique folder names for Azure blob storage, and naming limitations says we cannot use upper case letters.

**Comment by tsenart** [comment]
ULID parsing is case insensitive as captured by this test: https://github.com/oklog/ulid/blob/master/ulid_test.go#L265

That makes it safe for you to simply call `strings.ToLower` on the generated ULID string.
