### ISSUE TITLE
`go test -bench=.' is failing

### ISSUE THREAD

**Issue by hsawhney-bst** [oklog/ulid#4]
env:
> GOARCH="amd64"
> GOBIN=""
> GOEXE=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOOS="darwin"
> GOPATH=???
> GORACE=""
> GOROOT="/usr/local/Cellar/go/1.7.4/libexec"
> GOTOOLDIR="/usr/local/Cellar/go/1.7.4/libexec/pkg/tool/darwin_amd64"
> CC="clang"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xd/pgmdc_gx2gd0m459yxc5gdr00000gn/T/go-build114248060=/tmp/go-build -gno-record-gcc-switches -fno-common"
> CXX="clang++"
> CGO_ENABLED="1"
> 

🚀: (master)>go test -bench=.
--- FAIL: TestTimestamp (0.00s)
ulid_test.go:287: got timestamp 4773815605011, want 281474976710655
--- FAIL: TestParseRobustness (0.00s)
ulid_test.go:245: runtime error: index out of range
ulid_test.go:260: #1: failed on input [26]uint8{0x1, 0xc0, 0x73, 0x62, 0x4a, 0xaf, 0x39, 0x78, 0x51, 0x4e, 0xf8, 0x44, 0x3b, 0xb2, 0xa8, 0x59, 0xc7, 0x5f, 0xc3, 0xcc, 0x6a, 0xf2, 0x6d, 0x5a, 0xaa, 0x20}
FAIL
exit status 1
FAIL	_/Users/hsawhney/code/ulid	4.985s
🚀: (master)>

**Comment by tsenart** [comment]
This doesn't happen with Go tip. I pushed https://github.com/oklog/ulid/commit/8b9f7b2e10851b5f1737ce00fa2bedc814e83934 in order to debug if what's happening is related to the Go version you're on.

**Comment by tsenart** [comment]
Hey, I can't reproduce this. Any ideas? https://travis-ci.org/oklog/ulid/jobs/185138941

**Comment by tsenart** [comment]
Are you sure you have a clean check-out of the repo?

**Comment by hsawhney-bst** [comment]
Opps - forgot to do `go get -u github.com/oklog/ulid' (-u was important)
