### ISSUE TITLE
New release with go.modules?

### ISSUE THREAD

**Issue by im-kulikov** [oklog/ulid#43]
Is it possible to make a new release with go.modules support?

cc: @tsenart / @peterbourgon

**Comment by vtolstov** [comment]
yes, will be nice!

**Comment by peterbourgon** [comment]
Note that the first release after adding Go modules support should bump the major version number.

**Comment by im-kulikov** [comment]
Not sure

**Comment by ronnylt** [comment]
After upgrading to the new  major version that has support for Go modules, I am getting this error:

`go: github.com/oklog/ulid/v2@v2.0.0: go.mod has non-.../v2 module path "github.com/oklog/ulid" (and .../v2/go.mod does not exist) at revision v2.0.0
go: error loading module requirements
`

**Comment by peterbourgon** [comment]
Oh yeah, I need to put v2 in the go.mod, one second.

**Comment by peterbourgon** [comment]
@ronnylt Can you try with latest v2.0.1?

**Comment by ronnylt** [comment]
@peterbourgon it's working now! Thanks.
