### ISSUE TITLE
go get github.com/oklog/ulid/v2

### ISSUE THREAD

**Issue by hiqsociety** [oklog/ulid#50]
getting this error: how to resolve when i did 
go get github.com/oklog/ulid/v2

package github.com/oklog/ulid/v2: cannot find package "github.com/oklog/ulid/v2" in any of:
	/usr/lib/go-1.10/src/github.com/oklog/ulid/v2 (from $GOROOT)
	/root/go/src/github.com/oklog/ulid/v2 (from $GOPATH)

**Comment by peterbourgon** [comment]
Upgrade your Go to a more recent version that understands modules.

**Comment by jpramirez** [comment]
I'm having the same issue with go1.13.1 fresh install.
` ➜  ~ go get github.com/oklog/ulid/v2
package github.com/oklog/ulid/v2: cannot find package "github.com/oklog/ulid/v2" in any of:
	/usr/local/go/src/github.com/oklog/ulid/v2 (from $GOROOT)
	/home/[user]/projects/src/github.com/oklog/ulid/v2 (from $GOPATH)

➜  ~ 
`

**Comment by peterbourgon** [comment]
What is the result of 

```sh
env GO111MODULE=on go get github.com/oklog/ulid/v2
```

**Comment by er3636** [comment]
Hi! 
I'm having the same issue with go1.15.5 windows/amd64.
I didn't get this error in the past, but now I do.
I wonder why...

**Comment by er3636** [comment]
> Hi!
> I'm having the same issue with go1.15.5 windows/amd64.
> I didn't get this error in the past, but now I do.
> I wonder why...

I  solved the problem by using this command on Windows :```$env:GO111MODULE="on"```
