### ISSUE TITLE
can you post some example on usage?

### ISSUE THREAD

**Issue by hiqsociety** [oklog/ulid#51]
can you post some example on usage?

i'm interested in the return value of string etc

**Comment by hiqsociety** [comment]
Your only example is always showing the same id, can you provide example of randomly generated id?

**Comment by peterbourgon** [comment]
```go
func ExampleULID() {
	t := time.Unix(1000000, 0)
	entropy := ulid.Monotonic(rand.New(rand.NewSource(t.UnixNano())), 0)
	fmt.Println(ulid.MustNew(ulid.Timestamp(t), entropy))
	// Output: 0000XSNJG0MQJHBF4QX1EFD6Y3
}
```

This example code uses a fixed time for the time component and the entropy seed, so that the output is deterministic. For normal use, you would pass time.Now() instead of t for the time component, and use math/rand or crypto/rand for entropy.

```go
var (
	seed      = time.Now().UnixNano()
	entropy   = rand.New(rand.NewSource(seed))
	timestamp = ulid.Timestamp(time.Now())
)
u := ulid.MustNew(timestamp, entropy)
fmt.Printf("String form: %s\n", u.String())
fmt.Printf("Hex form: %x\n", u)
// etc.
```

Does this help?

**Comment by hiqsociety** [comment]
yes thank you. pls put into the main readme

but is this the optimum / fastest / recommended way to generate good fast ulid using this software?

**Comment by hiqsociety** [comment]
can you provide an example to use 
"crypto/rand"?

**Comment by peterbourgon** [comment]
[ulid.New](https://godoc.org/github.com/oklog/ulid#New) and [ulid.MustNew](https://godoc.org/github.com/oklog/ulid#MustNew) take an entropy as an io.Reader. Maybe you can look at the [crypto/rand](https://golang.org/pkg/crypto/rand) documentation and see if you can find something that satisfies the io.Reader interface? Hint: check out [package variables](https://golang.org/pkg/crypto/rand/#pkg-variables).

**Comment by hiqsociety** [comment]
are you saying that rand is good enough? shouldnt we use crypto/rand better?

**Comment by peterbourgon** [comment]
crypto/rand will be more secure but slower; math/rand will be less secure but faster. There is no “best”, only what is more appropriate for your use case.

**Comment by hiqsociety** [comment]
can you provide the example for crypto/rand . more secure version? 
would like to know what's the most appropriate and standard way to implement this.

**Comment by peterbourgon** [comment]
I’ve given you enough information to figure it out yourself. Good luck!
