### ISSUE TITLE
I would like to change the 80 bit section to 48 bit, which part is it safe to change?

### ISSUE THREAD

**Issue by hiqsociety** [oklog/ulid#52]
I would like to have a 12byte total length of ulid so instead of 80bit, i would like it to be 48 bit for the random id. where is it safe to change this? pls give your opinion. thank you.

1. type uint80 struct {
        Hi uint16
        Lo uint64 // <- should i change here? to uint32?
}

2. or here

     const EncodedSize = 26 //<- if so, what should i change to?

**Comment by peterbourgon** [comment]
GitHub issues are not the right place for this kind of question.
