### ISSUE TITLE
Issues generating ULID with freq. <1ms

### ISSUE THREAD

**Issue by mpmlj** [oklog/ulid#6]
Hi,

I've been experimenting with your library to generate ULIDs as keys for a database.
My code was doing 20+ row insertions per 1ms, and results, i.e. row ULIDs, are not in a strict sequence, not sorted (image below).
I was suggested that this may be due to "Within the same millisecond, sort order is not guaranteed" on https://github.com/alizain/ulid which, as I understand, served as a basis for oklog/ulid.

Could you please confirm (or not) randomness within 1 ms?
_If not_, below is my code, I would appreciate your check if IDs are generated correctly:

````Go
func GetNewID() string {
	entropy := rand.New(rand.NewSource(time.Now().UnixNano()))
	value := ulid.MustNew(ulid.Now(), entropy)
	return value.String()
}
````

This is a select in descending order by id (generated by ULID), where post_id column is filled with a "for" loop key. With correct generation, post_id should be a in a strict desc. order.
<img width="355" alt="screen shot 2017-02-20 at 11 34 06 pm" src="https://cloud.githubusercontent.com/assets/6718777/23151667/cc34a464-f7ca-11e6-989e-bfc5d0d34b99.png">

Thank you!
D.

**Comment by tsenart** [comment]
Yes, as per documentation, lexicographical order is only guaranteed in millisecond precision. Do you any suggestions on how to change the wording to make it more clear?

**Comment by mpmlj** [comment]
@tsenart hey, sorry for late reply, actually wording is totally clear - let's just make it is visible in the documentation of this package.

**Comment by alizain** [comment]
Stumbled upon this issue after looking into unrelated things.

@tsenart - I've spec'ed out and implemented strictly monotonic ULIDs, that would solve @mpmlj's problem. Are you interested in porting it over?

**Comment by tsenart** [comment]
@alizain: Backwards compatible?

**Comment by alizain** [comment]
Yes, the change to the spec itself is completely backwards compatible. To do it, you essentially have to incrememnet the random component by one bit.

**Comment by tsenart** [comment]
Would you contribute the change here?

**Comment by alizain** [comment]
Sure! I’ve been meaning to learn go, this will be a good chance to.

**Comment by aybabtme** [comment]
@alizain @tsenart just hit the same issue too, assumed that ULIDs were monotonically increasing within a process. would be very interested in how you approach this @alizain, happy to contribute a patch myself if you have the spec change somewhere.

**Comment by aybabtme** [comment]
@tsenart I have a sketch that looks like https://gist.github.com/aybabtme/fd24b8fce343c6209422bf364e5da46d. API/naming preferences aside, this implements the scheme described by @alizain on `oklog/ulid`
