### ISSUE TITLE
No need to set timezone

### ISSUE THREAD

**Issue by ash2k** [oklog/ulid#63]
I think unix timestamp does not depend on the timezone so there is no need to set it here: https://github.com/oklog/ulid/blob/master/ulid.go#L397

https://play.golang.org/p/AbtZT5gO7Vt:
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	x1 := time.Now().UTC()
	location, err := time.LoadLocation("America/New_York")
	if err != nil {
		panic(err)
	}
	x2 := x1.In(location)

	fmt.Printf("%s != %s\n", x1, x2)
	fmt.Printf("%d == %d\n", x1.Unix(), x2.Unix())
	fmt.Printf("%d == %d\n", x1.Nanosecond(), x2.Nanosecond())

}
```
prints:
```
2009-11-10 23:00:00 +0000 UTC != 2009-11-10 18:00:00 -0500 EST
1257894000 == 1257894000
0 == 0
```
Locally I get (because play.golang.org has some fancy clock):
```
2020-11-04 05:49:17.319471 +0000 UTC == 2020-11-04 00:49:17.319471 -0500 EST
1604468957 == 1604468957
319471000 == 319471000
```

**Comment by peterbourgon** [comment]
You're right, but it does no harm, and is symmetric with the other time-related functions in the API, which are explicit about this kind of thing. I'm going to close, but feel free to make a PR if it really really bugs you :)
