### ISSUE TITLE
Why not make MonotonicRead thread safe?

### ISSUE THREAD

**Issue by Scratch-net** [oklog/ulid#72]
It's easy to wrap it into a lock, isn't it? Or at least add such an option if speed is an issue. I could make a PR if it's ok with you

**Comment by peterbourgon** [comment]
Feel free to reopen with details.

**Comment by frederikhors** [comment]
Wow.

This is a big problem if there are inexperienced but passionate people like me.

@peterbourgon, can I ask you for an example code to be safe when using ulid with various goroutines?
