### ISSUE TITLE
Support parsing UUID strings

### ISSUE THREAD

**Issue by dan-j** [oklog/ulid#76]
Has there been any consideration into allowing string UUIDs be parsed within the unexported `parse` function: `func parse(v []byte, strict bool, id *ULID) error`

The reason I'm raising this is because I'd like to use this library for my primary keys, however CockroachDB returns UUID columns as UUID strings, not `[]byte`, so `ulid.ULID#Scan(src)` fails to parse the value.

My workaround is to implement a wrapper `ULID` type which has a `Scan` function (implementation shown below) however it would be nice to not have to do this, as I have to do things like `ULID{ULID: ulid.MustParse(...)}` which is a real annoyance:

```go
func (id *ULID) Scan(src interface{}) error {
	if str, ok := src.(string); ok {
		if len(str) != ulid.EncodedSize {
			bytes, err := uuid.Parse(str)
			if err != nil {
				return err
			}

			return id.UnmarshalBinary(bytes[:])
		}
	}

	return id.ULID.Scan(src)
}
```

If you don't want to implement UUID parsing or add an extra dependency, how about some mechanism where users can register custom parsers?

**Comment by peterbourgon** [comment]
Does [ulid.Parse](https://pkg.go.dev/github.com/oklog/ulid/v2#Parse) not so it for you?

**Comment by peterbourgon** [comment]
Please also be aware that ULIDs and UUIDs are _not_ interchangeable.

**Comment by dan-j** [comment]
Yeah, if CockroachDB returned UUID types as a `[16]byte` over the wire then everything would be fine, but it doesn't (not without a cast on the statement, which doesn't seem trivial using Gorm).

Yeah my own package is exactly what I wanted to avoid.

I was going to suggest some extension mechanism which allows users to define custom parse functions which could be fallen back to on error, or override the internal parse function entirely, but after drafting a bit of code none of the solutions are particularly nice 😅

**Comment by peterbourgon** [comment]
> Yeah my own package is exactly what I wanted to avoid.

It doesn't even need to be a package, really, it could just be a function...

```go
func UUID2ULID(s string) (ulid.ULID, error) {
    a, err := uuid.Parse(s)
    return ulid.ULID(a), err
}
```

But I really want to emphasize this is not valid, because...

> I was going to suggest some extension mechanism which allows users to define custom parse functions which could be fallen back to on error, or override the internal parse function entirely

As far as I understand, it's not possible to define a custom parsing function, because ULIDs have a well-defined layout in memory, and a well-defined encoding when represented as a string. Can you say more?

**Comment by dan-j** [comment]
It does need to be my own package, because I have a database model using gorm like:

```go
type MyModel struct {
    ID ulid.ULID `gorm:"primaryKey;type:uuid"`
    ...
```

When gorm scans the SQL result into the struct, it uses the `sql.Scanner` interface to marshal the data from the database into the struct.

In this package, `ULID.Scan(src)` only accepts a ULID-encoded string, or a `[]byte`. But CockroachDB sends the data as a UUID string.

A workaround is to use a `TEXT` type on the database table instead of `UUID`, then the database would return ULID-encoded strings and everything would work. However, this increases storage of the column since CockroachDB stores UUIDs as `[16]byte` under the hood so we gain an optimisation if using the `UUID` type.

**Comment by dan-j** [comment]
On the extension point, you could have a `uuidParse` function which defaults to nil, and allow users to set at runtime. In the internal parse, you could say if the `uuidParse` function is set and src isn't the right length, call it. Then users can bring their own UUID dependency if they want to use it, and nothing changes if users don't want it.

```go
var uuidParse UUIDParseFunc

type UUIDParseFunc func(src string) ([]byte, error)

// update parse as so
func parse(v []byte, strict bool, id *ULID) error {
	// Check if a base32 encoded ULID is the right length.
	if len(v) != EncodedSize {
		if uuidParse != nil {
			uuid, err := uuidParse(string(v))
			if err != nil {
				return err
			}
			
			*id = uuid
			return nil
		}
		return ErrDataSize
	}
        
        // rest of function below ...
}
```

Like I said earlier, no extension mechanism is exactly pretty, and accept if you didn't want to support this. But prompting the discussion anyway 🙂

**Comment by peterbourgon** [comment]
Alas, ULIDs and UUIDs aren't interchangeable in this way — you can't just take the 16 bytes of a UUID and parse it as a ULID. They may be the same size in memory but the semantics of the bytes are different.

But if you really insist 😉 it's super easy. Just define a wrapper type with a Scan method that does what you want.

```go
type ULID ulid.ULID

func (id *ULID) Scan(src interface{}) error {
    // parse your UUID type here
}
```

I think that's the same amount of effort and code as the parse approach would be.

**Comment by dan-j** [comment]
> Alas, ULIDs and UUIDs aren't interchangeable in this way — you can't just take the 16 bytes of a UUID and parse it as a ULID. They may be the same size in memory but the semantics of the bytes are different.

I get what you're saying, but in my use case they are. In other words, all ULIDs are valid UUIDs, not all UUIDs are valid ULIDs.

When my model is written to the database as per my previous comment, a `[]byte` is sent to the database for that ULID, and the database validates the `[]byte` is a UUID (which it is, since all ULIDs are UUIDs at the byte level). But when read back, the database sends a UUID-encoded string over the wire. In this case, that UUID is also valid ULID.

And yeah, the wrapper is what I've implemented so far, just I've had to reimplement every exported function defined on the package too, which means I need to maintain it going forwards as this library changes (which granted isn't very often).

For example, I've had to do this:

```go
```

**Comment by dan-j** [comment]
I'm happy for you to close this, it doesn't look like we're going to resolve the issue. But thanks for the discussion anyway, good to see people still active on the project 🙂

**Comment by peterbourgon** [comment]
Gotcha. But you only need all this stuff so that you can Scan a UUID string into the type, right? If so, I think you can get by with a simple type declaration and the single method — the new type should remain assignable to ulid.ULID, so you only need to use it in your models, and can use the regular version everywhere else. I think?

**Comment by peterbourgon** [comment]
Playing with that idea a bit, I realize I may have overstated how easy it would be 😅 

In any case, I'm pretty confident this module should not offer the ability to bring-your-own parser.
