### ISSUE TITLE
Empty value availability

### ISSUE THREAD

**Issue by ivanjaros** [oklog/ulid#84]
Is there an "empty" value that would pass the validation? Something like uuid v4 has with 00000000-0000-4000-0000-000000000000.

**Comment by peterbourgon** [comment]
What does "empty" mean?

**Comment by ivanjaros** [comment]
i guess "default" or "zero" value would be more appropriate rather than empty. like in go 0 for int or false for bool.

**Comment by peterbourgon** [comment]
I think you're referring to the zero value of the type, which for a ULID is 16 contiguous 0 bytes. You can construct a zero-value ULID same as any other type:

```go
var zeroint int // 0
var zerobool bool // false
var zeroid ulid.ULID // 00000000000000000000000000
```

The zero value of a ULID is valid, representing the timestamp `1970-01-01 00:00:00 +0000 UTC` with entropy of zero.

Does this answer your question?

**Comment by ivanjaros** [comment]
Yes, thank you. That is exactly what I was after.
