### ISSUE TITLE
big bug: ulid is alway not sortable

### ISSUE THREAD

**Issue by ABOB9** [oklog/ulid#91]
var list = make([]string, 0)
var monotonic = ulid.Monotonic(rand.New(rand.NewSource(time.Now().UnixNano())), 1)
var busy = make(chan bool, 1)

func AddUlid2List(index string) {
	busy <- true
	id, _ := ulid.New(ulid.Timestamp(time.Now()), monotonic)
	list = append(list, id.String()+" "+index)
	<-busy
}

func Test_test6(t *testing.T) {
	wg := sync.WaitGroup{}
	wg.Add(2)
	go func() {
		for i := 0; i < 1000000; i++ {
			AddUlid2List("1")
		}
		wg.Done()
	}()
	go func() {
		for i := 0; i < 1000000; i++ {
			AddUlid2List("2")
		}
		wg.Done()
	}()
	wg.Wait()
	for i := 0; i < len(list); i++ {
		if i+1 < len(list) && list[i] > list[i+1] {
			//63718 01GH13A2V6MBDBNBG8TSH0B0ZD 2 01GH13A2V5W3TXG0EX5GF9Q4MP 1
			fmt.Println(i, list[i], list[i+1])
			t.Error("big bug")
		}
	}
	if list[len(list)-2] > list[len(list)-1] {
		t.Error("big bug2")
		fmt.Println(list[len(list)-2], list[len(list)-1])
	}
	fmt.Println("END")
}

func Test_ulid(t *testing.T) {
	i := 0
	for {
		i++
		Test_test6(t)
		if i == 10 {
			break
		}
	}
}

**run the method Test_ulid, it print:**
63718 01GH13A2V6MBDBNBG8TSH0B0ZD 2 01GH13A2V5W3TXG0EX5GF9Q4MP 1
big bug

**Comment by peterbourgon** [comment]
I translated your code to [this program](https://gist.github.com/peterbourgon/e0f41ad6d2f74930a9aea546c64c582d) and ran it in a loop for several minutes. It never panicked. If this doesn't match your experience, can you please tell me what changes I should make to my program in order to get it to fail?

**Comment by peterbourgon** [comment]
It's also worth noting that you're not checking the error returned by ulid.New.

```go
id, _ := ulid.New(ulid.Timestamp(time.Now()), monotonic)
```

You need to check that error. If it's non-nil, then the returned ID is not valid and must not be used. Errors can happen for many reasons, including failures from the source of entropy. The monotonic entropy source will [return an error](https://github.com/oklog/ulid/blob/v2.1.0/ulid.go#L607-L616) in certain circumstances.

**Comment by ABOB9** [comment]
**I change the code, sometimes it is not sortable,the code:**

package main

import (
	"fmt"
	"github.com/oklog/ulid/v2"
	"math/rand"
	"os"
	"sync"
	"time"
)

var monotonic = ulid.Monotonic(rand.New(rand.NewSource(time.Now().UnixNano())), 1)
var busy = make(chan bool, 1)
var list = make([]string, 0)

func main() {
	i := 0
	for {
		i++
		MultiGoroutines()
		fmt.Println("the", i, "round is over,the length of list is", len(list))
		if i == 10 {
			break
		}
	}
}
func AddUlid2List(index string) {
	busy <- true
	id, err := ulid.New(ulid.Timestamp(time.Now()), monotonic)
	if err != nil {
		fmt.Println("error:", err.Error())
		os.Exit(1)
	}
	list = append(list, id.String()+" "+index)
	<-busy
}

func MultiGoroutines() {
	wg := sync.WaitGroup{}
	wg.Add(2)
	go func() {
		for i := 0; i < 1000000; i++ {
			AddUlid2List("1")
		}
		wg.Done()
	}()
	go func() {
		for i := 0; i < 1000000; i++ {
			AddUlid2List("2")
		}
		wg.Done()
	}()
	wg.Wait()
	for i := 0; i < len(list); i++ {
		if i+1 < len(list) && list[i] > list[i+1] {
			fmt.Println(i, list[i], list[i+1])
			fmt.Println("big bug")
		}
	}
	if list[len(list)-2] > list[len(list)-1] {
		fmt.Println("big bug2")
		fmt.Println(list[len(list)-2], list[len(list)-1])
	}
}

**It print as following:** 
the 1 round is over,the length of list is 2000000
the 2 round is over,the length of list is 4000000
the 3 round is over,the length of list is 6000000
the 4 round is over,the length of list is 8000000
the 5 round is over,the length of list is 10000000
the 6 round is over,the length of list is 12000000
the 7 round is over,the length of list is 14000000
the 8 round is over,the length of list is 16000000
16206789 01GH8HCH8M15TRZ7W2DXHMHFEY 1 01GH8HCH8KEJ5WPT42YC8ATEPC 2
big bug
the 9 round is over,the length of list is 18000000
16206789 01GH8HCH8M15TRZ7W2DXHMHFEY 1 01GH8HCH8KEJ5WPT42YC8ATEPC 2
big bug
the 10 round is over,the length of list is 20000000

**Comment by ABOB9** [comment]
**sometime,the print is:**
the 1 round is over,the length of list is 2000000
the 2 round is over,the length of list is 4000000
the 3 round is over,the length of list is 6000000
7187008 01GH8HYFQC10XQFZDM25S9GS22 1 01GH8HYFQBZBJYF4VFE05MESJT 2
big bug
the 4 round is over,the length of list is 8000000
7187008 01GH8HYFQC10XQFZDM25S9GS22 1 01GH8HYFQBZBJYF4VFE05MESJT 2
big bug
the 5 round is over,the length of list is 10000000
7187008 01GH8HYFQC10XQFZDM25S9GS22 1 01GH8HYFQBZBJYF4VFE05MESJT 2
big bug
the 6 round is over,the length of list is 12000000
7187008 01GH8HYFQC10XQFZDM25S9GS22 1 01GH8HYFQBZBJYF4VFE05MESJT 2
big bug
the 7 round is over,the length of list is 14000000
7187008 01GH8HYFQC10XQFZDM25S9GS22 1 01GH8HYFQBZBJYF4VFE05MESJT 2
big bug
the 8 round is over,the length of list is 16000000
7187008 01GH8HYFQC10XQFZDM25S9GS22 1 01GH8HYFQBZBJYF4VFE05MESJT 2
big bug
the 9 round is over,the length of list is 18000000
7187008 01GH8HYFQC10XQFZDM25S9GS22 1 01GH8HYFQBZBJYF4VFE05MESJT 2
big bug
the 10 round is over,the length of list is 20000000

**Comment by ABOB9** [comment]
**sometimes,it is:**

413730 01GH8JAMXZ1S8WNB06AECVEV4W 2 01GH8JAMXYHV79V19YA1K01G8Y 1
big bug
the 1 round is over,the length of list is 2000000
413730 01GH8JAMXZ1S8WNB06AECVEV4W 2 01GH8JAMXYHV79V19YA1K01G8Y 1
big bug
the 2 round is over,the length of list is 4000000
413730 01GH8JAMXZ1S8WNB06AECVEV4W 2 01GH8JAMXYHV79V19YA1K01G8Y 1
big bug
the 3 round is over,the length of list is 6000000
413730 01GH8JAMXZ1S8WNB06AECVEV4W 2 01GH8JAMXYHV79V19YA1K01G8Y 1
big bug
the 4 round is over,the length of list is 8000000
413730 01GH8JAMXZ1S8WNB06AECVEV4W 2 01GH8JAMXYHV79V19YA1K01G8Y 1
big bug
the 5 round is over,the length of list is 10000000
413730 01GH8JAMXZ1S8WNB06AECVEV4W 2 01GH8JAMXYHV79V19YA1K01G8Y 1
big bug
the 6 round is over,the length of list is 12000000
413730 01GH8JAMXZ1S8WNB06AECVEV4W 2 01GH8JAMXYHV79V19YA1K01G8Y 1
big bug
the 7 round is over,the length of list is 14000000
413730 01GH8JAMXZ1S8WNB06AECVEV4W 2 01GH8JAMXYHV79V19YA1K01G8Y 1
big bug
the 8 round is over,the length of list is 16000000
413730 01GH8JAMXZ1S8WNB06AECVEV4W 2 01GH8JAMXYHV79V19YA1K01G8Y 1
big bug
the 9 round is over,the length of list is 18000000
413730 01GH8JAMXZ1S8WNB06AECVEV4W 2 01GH8JAMXYHV79V19YA1K01G8Y 1
big bug
the 10 round is over,the length of list is 20000000

**Comment by ABOB9** [comment]
**sometimes it is sortable, the print is:**
the 1 round is over,the length of list is 2000000
the 2 round is over,the length of list is 4000000
the 3 round is over,the length of list is 6000000
the 4 round is over,the length of list is 8000000
the 5 round is over,the length of list is 10000000
the 6 round is over,the length of list is 12000000
the 7 round is over,the length of list is 14000000
the 8 round is over,the length of list is 16000000
the 9 round is over,the length of list is 18000000
the 10 round is over,the length of list is 20000000

**Comment by ABOB9** [comment]
> I translated your code to [this program](https://gist.github.com/peterbourgon/e0f41ad6d2f74930a9aea546c64c582d) and ran it in a loop for several minutes. It never panicked. If this doesn't match your experience, can you please tell me what changes I should make to my program in order to get it to fail?

your code is no problem, ulid.New method not return a error.  
this bug is haphazard.

**Comment by peterbourgon** [comment]
I've run your modified code for several minutes on a few different operating systems and architectures, and have not been able to reproduce your results.

The output you're providing appears to always show "big bug" with the same initial `i` value. [In this comment](https://github.com/oklog/ulid/issues/91#issuecomment-1305220514) that value is 16206789. [In this comment](https://github.com/oklog/ulid/issues/91#issuecomment-1305227514) that value is 7187008. And so on. This strongly suggests that the code you've pasted into your comments is not the complete code that you're running to produce that output.

If you want to continue this issue, please re-open the issue with a link to a repo or GitHub gist that is directly executable and reproduces the problem. Please **do not** copy and paste code into the comment box of this issue.
